services:

  postgres:
    image: postgres
    container_name: futsal-draw-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-futsal_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-futsal_password}
      POSTGRES_DB: ${POSTGRES_DB:-db_futsal_draw_system_api}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/migration/init:/docker-entrypoint-initdb.d
    networks:
      - futsal-draw-system-api-network
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - futsal-draw-system-api-network
    depends_on:
      - postgres

networks:
  futsal-draw-system-api-network:
    name: futsal-draw-system-api-network
    driver: bridge
volumes:

  postgres:
    name: postgres-volume
  pgadmin:
    name: pgadmin-volume