
spring.datasource.url=jdbc:postgresql://localhost:5432/db_futsal_draw_system_api
spring.datasource.username=futsal_user
spring.datasource.password=futsal_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/init

